version: '3.8'

services:
    # PostgreSQL Database Service
    data-catalog-db:
        container_name: data-catalog-db
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck: # Ensure Postgres is ready before dependent services start
            test: ['CMD-SHELL', 'pg_isready -U user -d db']
            interval: 10s
            retries: 5
            start_period: 20s
        networks:
            - data-catalog-network  # Connect to the custom network

    # Application Service
    app:
        build: .
        container_name: data-catalog-app
        ports:
            - '3000:3000'
        environment:
            - PORT=3000
            - DB_USER=user
            - DB_PASS=password
            - DB_HOST=data-catalog-db
            - DB_NAME=db
            - DB_PORT=5432
        depends_on: # Ensure the database is healthy before starting the app
            data-catalog-db:
                condition: service_healthy
        networks:
            - data-catalog-network  # Connect to the same network as the database

volumes:
    postgres_data:

# Define a custom network to isolate the services
networks:
  data-catalog-network: